version: '3'

services:

    node:
        build: ./
        restart: always
        working_dir: /var/www/athena_pallas_audio_bot/app
        entrypoint: sh -c "npm ci --no-audit --no-fund ; npm start"
        volumes:
            - ./:/var/www/athena_pallas_audio_bot
